#!/bin/bash

# Defaults to _k3s-install-systemd_. Please refer to its doc for more info.
function k3s-install() {

  k3s-install-systemd

}

# Install _k3s_ using the official [docker-compose.yml](https://github.com/rancher/k3s/blob/master/docker-compose.yml) and current's dir _.env_ if any.
#
# Examples:
#
#   ```
#   k3s-install-docker-compose
#   k3s-install-docker-compose --scale node=3
#   ```
function k3s-install-docker-compose() {

  k8sb-check-tool curl || return 1
  k8sb-check-tool docker-compose || return 1

  ARGS="$@"
  DOCKER_COMPOSE_ARGS="${ARGS}"
  DOCKER_COMPOSE_URL="https://raw.githubusercontent.com/rancher/k3s/master/docker-compose.yml"
  DOCKER_COMPOSE_FILE="/var/tmp/k3s-docker-compose.yml"

  curl -so "$DOCKER_COMPOSE_FILE" "$DOCKER_COMPOSE_URL"

  docker-compose -f "${DOCKER_COMPOSE_FILE}" up ${DOCKER_COMPOSE_ARGS}

}

# Install _k3s_ using the the official [install.sh script](https://github.com/rancher/k3s#systemd).
# To provide any of the supported environment variables, export them before
# executing this function or in case a _.env_ exists in the current dir, it
# will be used.
#
# Examples:
#
#   ```
#   export INSTALL_K3S_VERSION=vX.Y.Z
#   k3s-install-systemd
#   ```
function k3s-install-systemd() {

  pgrep -f k3s.*server &> /dev/null
  if [ $? -eq 0 ]
  then
    echo "[!] k3s seems already installed!"
    return 0
  else
    k8sb-check-tool curl || return 1
    curl -sfL https://get.k3s.io -o /tmp/k3s-install.sh
    chmod +x /tmp/k3s-install.sh
    bash -c 'test -e .env && source .env; /tmp/k3s-install.sh'
  fi

}

# Tries to uninstall 'k3s' using the official uninstall script or bringing down
# the docker-compose and *all the volumes associated*.
function k3s-uninstall() {

  which k3s-uninstall.sh 2> /dev/null
  if [ $? -eq 0 ]
  then
    sudo k3s-uninstall.sh
  else
    k8sb-check-tool docker-compose || return 1
    DOCKER_COMPOSE_FILE="/var/tmp/k3s-docker-compose.yml"
    docker-compose -f ${DOCKER_COMPOSE_FILE} down -v
  fi

}
