#!/bin/bash

function kustomize-get-fullpath-for-dir() {

  DIR="$@"
  REALPATH_CMD=$(get-realpath-cmd)
  FULL_PATH_MODULE=$(${REALPATH_CMD} "${DIR}")
  echo "${FULL_PATH_MODULE}"

}

function kustomize-local-chart() {

    export KUSTOMIZE_DIR="$1";
    if [ -z "$HELM_CHART_HOME" ] || [ -z "$HELM_RELEASE_NAME" ] || [ -z "$HELM_NAMESPACE" ]; then
        echo "Usage: HELM_CHART_HOME=~/Projects/gitlab/charts HELM_RELEASE_NAME=init0 HELM_NAMESPACE=development $FUNCNAME /path/to/your/kustomization/dir";
        echo -e "\n - Optionally, set a 'valuesFile=/path/to/your/values.yaml' to set helm chart values from it";
        return 1
    fi;
    export chartHome=$HELM_CHART_HOME;
    export releaseName=$HELM_RELEASE_NAME;
    export releaseNamespace=$HELM_NAMESPACE;
    KUSTOMIZE_DIR_FULL_PATH=$(kustomize-get-fullpath-for-dir ${KUSTOMIZE_DIR});
    export XDG_CONFIG_HOME="${KUSTOMIZE_DIR_FULL_PATH}/.kustomize";
    kustomize-download-chart-inflator-plugin "${XDG_CONFIG_HOME}";
    envsubst < assets/k8s-kustomizations/helm-charts/base/local-chartInflator.yaml.tpl > ${KUSTOMIZE_DIR}/chartInflator.yaml;
    kustomize build --enable_alpha_plugins "${KUSTOMIZE_DIR}"
}

function kustomize-remote-chart() {

    if [ -z "$HELM_CHART_NAME" ] ; then
        echo "Usage: HELM_CHART_NAME=redis [HELM_CHART_RELEASE=stable HELM_CHART_VERSION=0.23.0 HELM_RELEASE_NAME=init0 HELM_NAMESPACE=default] $FUNCNAME /path/to/your/kustomization/dir";
        echo -e "\n - Optionally, set a 'valuesFile=/path/to/your/values.yaml' to set helm chart values from it";
        return 1
    fi;
    export chartRelease=$HELM_CHART_RELEASE;
    if [ ! -z "$HELM_CHART_VERSION" ]
    then
      export chartVersion=$HELM_CHART_VERSION;
    else
      unset chartVersion
    fi
    export chartName=$HELM_CHART_NAME;
    export releaseName=$HELM_RELEASE_NAME;
    export releaseNamespace=$HELM_NAMESPACE;
    unset chartHome;
    KUSTOMIZE_DIR="$1";
    KUSTOMIZE_DIR_FULL_PATH=$(kustomize-get-fullpath-for-dir ${KUSTOMIZE_DIR});
    export XDG_CONFIG_HOME="${KUSTOMIZE_DIR_FULL_PATH}/.kustomize";
    kustomize-download-chart-inflator-plugin "${XDG_CONFIG_HOME}";
    envsubst < assets/k8s-kustomizations/helm-charts/base/remote-chartInflator.yaml.tpl > ${KUSTOMIZE_DIR}/chartInflator.yaml;
    kustomize build --enable_alpha_plugins "${KUSTOMIZE_DIR}"
}
