#!/bin/bash

function k8sb-check-tool() {

  which "$@" &> /dev/null
  if [ $? -ne 0 ]
  then
    echo "[!] '$@' not installed!"
    return 1
  fi

}

function get-realpath-cmd() {

  CURRENT_OS=$(uname -s)
  case "${CURRENT_OS}" in
    Darwin*)  REALPATH_CMD="realpath";;
    Linux*) REALPATH_CMD="readlink -f"; REALPATH_ARGS="-f";;
  esac

  echo $REALPATH_CMD $REALPATH_ARGS

}
